---
version: '3.4'
services:
  ci-infra:
    &ci-infra
    volumes:
      - .:/tf-eks
      - $HOME/.aws/credentials:/root/.aws/credentials 
    working_dir: /tf-eks
    build:
      context: .
      target: ci-infra

  terraform:
    <<: *ci-infra
    entrypoint: terraform

  aws:
    <<: *ci-infra
    entrypoint: aws
